language: c
before_install:
  - sudo apt-get install m4 llvm software-properties-common
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y opam
  - opam init
  - eval `opam config env`
  - opam install llvm.3.4 ocamlfind
script: make test
